# Generated by Django 4.1.7 on 2023-03-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_whichfoodplace_listing_nearbyfoodplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='video',
            field=models.FileField(blank=True, upload_to='video/%Y/%m/%d/'),
        ),
    ]
